### ISSUE TITLE
Fix unresolved links in 2.x docs

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#1839] opened 2021-03-29 06:07 UTC
Run the build in `docs` and you'll see a bunch of unresolved links. They are, in fact, unresolved.

**Comment by antonkw** [comment] 2021-05-07 15:39
@djspiewak 
Hello,
As far as I understood branch is 2.x.
What command I need to run to observe those errors.
I mean, you wrote `Run the build in ` but it's not clear what is that "build"
Thanks

**Comment by vasilmkd** [comment] 2021-05-07 15:53
Hi @antonkw. Please run the following commands to build the documentation:
```bash
git checkout docs
git submodule update --init --recursive
./build.sh host
```

Here you would probably see some warnings regarding unresolved links. Hope this is helpful.

**Comment by antonkw** [comment] 2021-05-07 16:59
@vasilmkd yes, I guess I reproduced that, thanks!

**Comment by antonkw** [comment] 2021-05-13 11:04
The fix is just removing `.md` extensions in links.

@vasilmkd what is the branching model?

I need to fix files at `versions/2.x/docs`. As far as I understand I should raise PR against `series/2.x` branch. That's correct?

I didn't work with git submodules. What I should use to update `docs` (for testing purposes) with latest `series/2.x`?

Thanks

**Comment by vasilmkd** [comment] 2021-05-13 11:09
Yes, open a PR against `series/2.x`.

If you want to test your solution, maybe you can try manually switching to the `docs` branch and updating the pages in `versions/2.x`? I think this is necessary because the submodules are created to link against `typelevel/cats-effect` which would not contain your changes. Not completely sure. Hope this helps.

**Comment by antonkw** [comment] 2021-05-13 15:57
@vasilmkd 
Here it is: https://github.com/typelevel/cats-effect/pull/1965
Please let me know if anything is wrong.

**Comment by vasilmkd** [comment] 2021-05-13 15:57
I saw it, I let the CI run :)

**Comment by vasilmkd** [comment] 2021-05-25 22:19
Fixed in #2005.

**Closed as completed** 2021-05-25 22:19 UTC
Labels: :books: docs, :older_man: CE2
