### ISSUE TITLE
Delaying a task to be run far into the future can prevent concurrently scheduled tasks from running

### ISSUE THREAD

**Issue by mperucca** [typelevel/cats-effect#3948] opened 2024-01-12 22:06 UTC
I reported a Java bug in [ScheduledExecutorService.schedule](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html#schedule-java.lang.Runnable-long-java.util.concurrent.TimeUnit-) (still under internal review) where scheduling a task far into the future can prevent other concurrent `schedule` calls from getting their tasks run at their designated times. After discovering this Java bug, I switched to trying to schedule concurrent tasks in the future with cats effect but then encountered the same bug (which makes sense since I then noticed that the scheduler is implemented with `ScheduledExecutorService`). The race condition can often be reproduced with the following code:

```scala
import scala.concurrent.duration.*
import cats.effect.*
import cats.effect.unsafe.implicits.global

val shortDelayTask = IO.unit.delayBy(Duration.Zero)
val longDelayTask = IO.unit.delayBy(Long.MaxValue.nanos)

(shortDelayTask race longDelayTask).unsafeRunSync() // this sometimes never finishes
```

The problem is that scheduling `longDelayTask` interferes with the scheduling of `shortDelayTask`, leading to `shortDelayTask` never running.

A workaround I've used is to either wrap the calls to `ScheduledExecutorService.schedule` in a `synchronized` block or to change extremely large delays to not so large ones (though I don't know the exact cutoff that prevents the bug).

**Comment by armanbilge** [comment] 2024-01-12 22:11
Thanks for reporting! What version of Cats Effect can you reproduce with?

> which makes sense since I then noticed that the scheduler is implemented with `ScheduledExecutorService`)

The reason I ask is because as of Cats Effect v3.5.0 the default `Scheduler` is actually the `WorkStealingThreadPool`. Further reading in the "integrated timers" section of the release notes:
https://github.com/typelevel/cats-effect/releases/tag/v3.5.0

**Comment by mperucca** [comment] 2024-01-12 22:27
Oh that's fantastic! I was on 3.4.8, and I can't reproduce the bug on 3.5.0. I definitely should have checked the version first. I'm grateful for my sake that I reported this but also sorry for your sake that I did :sweat_smile: .

**Comment by djspiewak** [comment] 2024-01-13 23:16
I'm going to mark this as a bug (it's valid!) but close it for now since we're winding down support on 3.4.x and it works on 3.5.x. If someone else comes across this issue, our recommendation would be to upgrade to 3.5 (or higher). If that's not an option for you and a fix is really urgent, please comment here (and ideally also flag it in the Discord) and we can backport a fix pretty easily. It doesn't seem difficult to fix, I'd just like to roll off that release line.

**Closed as completed by djspiewak** 2024-01-13 23:16 UTC
Labels: :beetle: bug
