### ISSUE TITLE
Add tracing support for ScalaJS

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#934] opened 2020-07-13 22:37 UTC
Although the tracing implementation compiles for ScalaJS, there isn't a great way to enable or test it yet. We're also not completely sure how stack traces work on that platform. ScalaJS applications can run in the browser or on the server, so we need to read in the configuration from the environment, the `window` object and/or the `global` object. Being able to set these in SBT is also crucial as we want to run the runtime tracing tests against it.

**Comment by djspiewak** [comment] 2021-08-30 20:37
Duplicate of #2146

**Closed by djspiewak** 2021-08-30 20:37 UTC
