### ISSUE TITLE
Hanging behaviour when lifting `promise.future` in certain conditions

### ISSUE THREAD

**Issue by Baccata** [typelevel/cats-effect#1463] opened 2020-11-29 09:18 UTC
* Scala 2.13.3
* cats-effect 2.3.0 
* jdk 8 

Hey folks. I'm currently performing a massive overhaul of weaver in preparation for CE3. I spent the last couple days trying to hunt down some non-deterministic behaviour (CE2) that was making some "dog-food" tests (ie testing weaver with weaver) hang forever.

After hours  of random stabs in the dark (I should really add that to my CV, it seems to be my main debugging skill), I've found that an effect lifting a promise's future was just "hanging" in certain conditions : 

`Async.fromFuture(Sync[F].delay(promise.future))` 

and that mapping the future seemed to fix the problem : 

`...delay(promise.future.map(_ => ())(ExecutionContext.global))`

I have yet to figure out a minimal reproduction, but removing the map call [here](https://github.com/disneystreaming/weaver-test/commit/6fc9540706527391e1e86f5b586352f9e2f48745#diff-1570d3a44aeb12203f27babfdfb3c7d73cd99313278ed3fff56af9b84a16625dR58) and running the following command in an SBT repl should show the problem (ie tests just hanging forever) : 

``` 
frameworkJVM/testOnly weaver.framework.test.DogFoodSuiteJVM
```

**Comment by djspiewak** [comment] 2020-11-29 21:59
Whelp…

Random stabs in the dark are definitely a CV entry btw. The more senior you are, the more likely your random desperation stabs are to surface some undiscovered weirdness. Never a guarantee though.

This is immensely strange. I want to stick some printlns in fromFuture to see if it's hanging before or after we enter that point.

**Comment by RaasAhsan** [comment] 2020-11-30 05:05
Out of curiosity, what is the configuration of the underlying `ContextShift`? We've certainly seen plenty of hanging and starvation bugs caused by lack of fairness

also, just to confirm: the program non-deterministically hangs without the `map` call, but deterministically succeeds when it is present?

**Comment by Baccata** [comment] 2020-11-30 09:08
> Out of curiosity, what is the configuration of the underlying ContextShift? We've certainly seen plenty of hanging and starvation bugs caused by lack of fairness 

global EC. I should probably switch it to something else before next version, but right now I'm just trying to get the new runner on par with the current. 

> also, just to confirm: the program non-deterministically hangs without the map call, but deterministically succeeds when it is present? 

I'd say it non-deterministically succeeds without the map call (like, such a low rate of success that calling non-deterministic is not accurate, hence why I renamed the issue), but seems to succeed all the time with the map call. 

#### Other things worth noting : 

* In the the case of this behaviour, the promise is fulfilled within a blocker (which also wraps an imperative loop). 
* Its future is lifted within a parTraverse call
* the blocking call is happening underneath a call to fs2.Stream#parEvalMap` (which delegates to CE's Concurrent instance). 
* calling `fs2.Stream#evalMap` instead (without `future.map`), whilst adding a `.start.flatMap(_.join)` to `blocker.delay`  prevents the hanging. 

(yes, this is really random information 😅 )

**Comment by Baccata** [comment] 2020-12-03 13:43
Here's a branch that exhibits the behaviour. `Async#fromFuture` was copied, with a minimal "immediate" EC on which the future's callback runs, mirroring CE's behaviour. 

https://github.com/disneystreaming/weaver-test/blob/ce2-promise-bug/modules/framework/src-jvm/PlatformRunner.scala#L56

The following sbt command can be ran a couple times, usually it hangs after 2 or 3 tries.  

> catsJVM/testOnly weaver.framework.test.DogfoodTests

**Comment by RaasAhsan** [comment] 2020-12-06 09:36
Alright, I believe I have a grasp on what's going on here, so let me jot it down before I forget it :) I can also produce a minimization if you want.

This hanging behavior is really a deadlock that manifests when the `onComplete` callback for the `promise.future` is registered _before_ the promise is completed. So assuming that condition, this bug manifests deterministically. That, along with the use of blocking threads and the trampolining EC makes for a lethal combination.

Here is the ordering of events under which we observe a deadlock:
1. The test runner starts up the test and waits for SBT to signal readiness: https://github.com/disneystreaming/weaver-test/blob/ce2-promise-bug/modules/framework/src-jvm/PlatformRunner.scala#L162. The future has not been completed yet (SBT isn't ready yet), so we register a callback on the `promise.future`, waiting on that. Note that by the definition of `fromFuture`, this callback will be invoked on the trampoline EC.
2. SBT signals to Weaver that the test is ready to execute and fulfills the `promise`: https://github.com/disneystreaming/weaver-test/blob/ce2-promise-bug/modules/framework/src-jvm/SbtTask.scala#L21 . 
3. When the promise is fulfilled, it invokes the callback that was registered earlier in step 1 on the trampoline EC, so it will effectively happen on the current thread. However! Assume that this `Task.execute` method is _already_ running within the trampolined EC. That means the completion of the callback will be pushed to the end of the internal queue, and we'll just return.
4. The callback not having been completed yet, the test runner moves on... and basically waits for the test run to signal back that it completed: https://github.com/disneystreaming/weaver-test/blob/ce2-promise-bug/modules/framework/src-jvm/SbtTask.scala#L25 . It'll busy loop and block on that, so the completion callback that was scheduled to happen later will never have a chance to execute.

You might now be wondering why we also deadlock when we use the inlined `fromFuture` method with a parasitic EC. Interesting fact about the CE2: the completion of an `async` callback itself is [submitted onto the trampolined execution context](https://github.com/typelevel/cats-effect/blob/series/2.x/core/shared/src/main/scala/cats/effect/internals/Callback.scala#L137). So even if the future completion doesn't happen on the trampoline, the actual completion of the async callback will.

This also explains why introducing a `map` on the `promise.future` on the global EC fixes things. The completion of the callback will occur asynchronously on another thread, where the trampolining has no effect.

So really this is a liveness failure where the callbacks on `promise.success()` are technically scheduled to run asynchronously, but never will. The fact that the callback is never execute is really subtle and is obscured by the many layers of abstraction and optimizations in CE2. The most obvious solution to me right now is to fulfill the `promise` asynchronously on another `ExecutionContext`. "Fixing" this on CE2 probably constitutes API breaking changes so we can't do anything there, but FWIW this wouldn't happen on CE3 because we don't perform any trampolining magic.

Just to gloat since I've been tackling a lot of these bugs lately: it took me 1 hour and 47 minutes to understand what was going on here :D

**Comment by Baccata** [comment] 2020-12-06 13:30
Thanks for the write up, this makes it a lot clearer 😸 . The lack of `EC` constraint of `Promise#future` did raise the question of "where the hell does does the callback run ?" in the case of an immediate EC, and the while-loop was the obvious suspect in  "who hung that thread ?", but I was unable to connect the dots between the two. 

I'm happy with no action being taken by the cats maintainers, the workaround of mapping `promise.future` works well enough, and the CE version on which the problem has been identified is bound to be deprecated.

> Just to gloat since I've been tackling a lot of these bugs lately: it took me 1 hour and 47 minutes to understand what was going on here :D

The gloat is well deserved 😄

**Comment by djspiewak** [comment] 2020-12-06 15:09
Jesus, Raas… This is impressive as hell.

I agree that, given the circumstances, the best approach is for Weaver to bounce through global on the callback (or really, any pool). I also concur it would be impossible to fix this from CE's side without breaking the API, and CE3 does exactly that and (broadly) implements the fix that would be needed.

**Closed as completed** 2020-12-06 15:09 UTC
