### ISSUE TITLE
Dispatcher allocation can hang forever

### ISSUE THREAD

**Issue by scf37** [typelevel/cats-effect#2926] opened 2022-03-29 09:05 UTC
cats-effect 3.3.9
In my project, second unsafeRunSync always hangs. When reproducing on Scastie, it either passes or hangs on first unsafeRunSync.

```scala
import cats.effect.std.Dispatcher
import cats.effect.{Async, IO, Resource}
import cats.effect.unsafe.implicits.global

println(1)
Dispatcher[IO].map { _ =>
  println(2)
}.allocated.unsafeRunSync() // can hang here

println(3)
Dispatcher[IO].map { _ =>
println(4)  
}.allocated.unsafeRunSync() // or here
```

https://scastie.scala-lang.org/65NZvvNKQcGfd8okMNNQMA

**Comment by vasilmkd** [comment] 2022-03-29 11:13
Can you please test if this is happening in 3.3.8 or maybe some other version too? It would be nice to find out if this is a bug for some time (possibly since the beginning) or a regression in the latest release. Thanks!

**Comment by scf37** [comment] 2022-03-29 11:25
On Scastie I tested 3.0, 3.1, 3.2, 3.3.0, 3.3.9

**Comment by vasilmkd** [comment] 2022-03-29 12:03
Reminds me of https://github.com/scala/bug/issues/9076.

**Comment by armanbilge** [comment] 2022-03-29 12:40
Yup, pretty sure it's this problem:
https://fs2.io/#/faq?id=why-does-stream-evaluation-sometimes-hang-in-the-repl

> In versions of Scala between 2.12.0 and 2.13.1, stream programs that call unsafeRunSync or other blocking operations sometimes hang in the REPL. This is a result of Scala's lambda encoding and was tracked in [SI-9076](https://issues.scala-lang.org/browse/SI-9076). The issue was fixed in Scala 2.13.2 (see [scala/scala#8748](https://github.com/scala/scala/pull/8748)).

**Comment by scf37** [comment] 2022-03-29 13:00
It fails on 2.13.8. Also, originally it hung up in large project combined with other `Resource`-s. All those `unsafeRunSync`-s are just to reproduce the bug.

(Un)fortunately, minimal example within sbt project works as expected.

**Comment by wjoel** [comment] 2022-04-04 08:27
It's not `Dispatcher` which is the problem, it's `cats.effect.unsafe.implicits.global` and `.unsafeRunSync()`. This can hang after printing `1`:
```scala
import cats.effect.std.Dispatcher
import cats.effect.{Async, IO, Resource}
import cats.effect.unsafe.implicits.global

println(1)
IO.println("hello").unsafeRunSync()
Dispatcher[IO].map { _ =>
  println(2)
}.allocated.unsafeRunSync()

println(3)
Dispatcher[IO].map { _ =>
println(4)  
}.allocated.unsafeRunSync()
```
https://scastie.scala-lang.org/AdxtHcz9RN68WO43bmYJtQ

**Comment by djspiewak** [comment] 2022-04-04 16:20
Is there any way we can reproduce this using a `def main`? Scastie and all REPLs have weirdness associated with initialization which could be at play here.

**Comment by scf37** [comment] 2022-04-04 19:49
Probably can be 'fixed' by using the same implementation for IOApp and unsafeRunXYZ. Current situation of completely different implementations for seems to be identical tasks is weird.

**Comment by djspiewak** [comment] 2022-04-04 23:19
> Current situation of completely different implementations for seems to be identical tasks is weird.

How so?

**Comment by djspiewak** [comment] 2023-02-27 18:03
Closing this for now. We really need a `def main` reproduction. Btw just in case anyone lands here from Google, replying to a subtle point quickly:

> Probably can be 'fixed' by using the same implementation for IOApp and unsafeRunXYZ

We do, sort of. All the `unsafeRun` variants use `unsafeRunFiber` under the surface, which is the same thing `IOApp` uses. However, because `IOApp` has the (soft) guarantee that it controls the very beginning and very end of the program, it is able to provide a lot more functionality, including things like fiber dumps, the `MainThread` executor, more deterministic fatal error reporting, <kbd>Ctrl</kbd>-<kbd>C</kbd> handling, and more. For this reason, `IOApp#main` will never be able to directly delegate to `unsafeRunSync`, and they already share as much of their implementations as is possible.

**Closed as completed by djspiewak** 2023-02-27 18:03 UTC
