### ISSUE TITLE
Release can be called more than once

### ISSUE THREAD

**Issue by RaasAhsan** [typelevel/cats-effect#384] opened 2018-09-29 23:13 UTC
Because of recent discussions, I have been tinkering around with `bracket` and cancellation. I think I've found some unfavorable behavior that can be illustrated by the following program:

```scala
object TestApp extends IOApp {

  import cats.implicits._
  import scala.concurrent.duration._

  def printLine(message: String): IO[Unit] =
    IO.delay(println(message))

  def blocking: IO[Unit] =
    IO.delay(Thread.sleep(3000))

  override def run(args: List[String]): IO[ExitCode] = for {
    _     <- printLine("start")
    io     = printLine("acquire").bracket(_ => blocking *> printLine("use"))(_ => printLine("release"))
    fiber <- io.start
    _     <- fiber.cancel
    _     <- IO.sleep(5.seconds)
  } yield ExitCode.Success

}
```

If you run the program, you should see the following output:
```
start
acquire
release
use
release
```

When the fiber is cancelled, the `IOConnection` is cancelled so its finalizers are executed (immediately?). However, if `use` does not encounter an cancellation boundary after the fiber is cancelled, [it will go on to run `release` again](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/internals/IOBracket.scala#L68). I can verify that the behavior is the same for `guarantee`.

I imagine one way to fix the double release is to insert a cancellation boundary before release, but I think there's the other problem of having the ability to reuse a resource that has already been released.

I haven't seen any discussion or documentation about this, so is this behavior something users of `IO` need to  keep in mind when using `bracket`, or is there an issue here?

**Comment by SystemFw** [comment] 2018-09-29 23:14
Interesting, I had a bug that made me suspect a similar behaviour, which I was meaning to investigate further.

**Comment by alexandru** [comment] 2018-10-01 04:39
Thanks for discovering this @RaasAhsan,

I think that yes, you are correct. In the transition to using `IO[Unit]` cancelation tokens internally, I missed the idempotency check.

I pushed a fix in https://github.com/typelevel/cats-effect/pull/376, please try it out.

**Comment by RaasAhsan** [comment] 2018-10-01 14:56
Great, release is being invoked only once now! Regarding the behavior of the ordering of these effects, is it correct that there is no guarantee that `use` completes before `release` is started?  The worst case being that a resource is released and then `use` attempts to use it again. I imagine this behavior can be tolerated in the face of cancellation though.

**Comment by alexandru** [comment] 2018-10-01 17:09
`release` happening before `use` has finished is a possibility via cancellation, but we pretend that it doesn’t happen.

Worst case scenario you get some race condition that you, as a user, can fix via synchronization. Like with a Semaphore or something.

Basically what we are doing right now is the best we can do.

**Closed** 2018-10-07 07:10 UTC

**Comment by jdegoes** [comment] 2018-10-07 15:18
@RaasAhsan 

In [ZIO](http://github.com/scalaz/scalaz-zio) you will get:

```
start
acquire
use
release
```

Or:

```
start
acquire
release
```

depending on whether or not `use` is interrupted (most likely it will be interrupted). Whether you interrupt or not, `release` will never occur before `use`.

When not interrupted, `use` executes fully before `release`, and when interrupted, `use` finishes execution (part of the way through) before `release`, ensuring that in either case, `use` is not running at the time when `release` is called.

Is this the behavior you're looking for or do you mean something else by concurrent `use` / `release`?

**Comment by jdegoes** [comment] 2018-10-07 22:57
I'm afraid my statement is correct. The thread executing `use` is **also** in charge of aggregating `release`, so they are necessarily sequenced, and without locks or performance overhead of any kind. 

Remember that cancellation doesn't work like interruption. Cancellation is a different model than interruption.

In particular, in `ZIO` the `use` (in this example) could be interrupted before it began, before the blocking sync IO, or right after (but before the print line). In all cases, `use` would be totally done executing before `release` began.

**Comment by RaasAhsan** [comment] 2018-10-07 23:46
@jdegoes Both of those sequences of execution seem intuitive to me. My expectation was that `release` cannot begin until `use` completes, which ZIO seems to satisfy. I suppose a decision had to be made for `IO` to execute finalizers immediately in the face of things like non-terminating tasks.

What is ZIO's behavior when you interrupt/cancel a `bracket` operation where `use` is non-terminating (ZIO equivalent of `IO.never`)? I imagine it halts, which I think is fine and is a design decision users need to be aware of.

> Remember that cancellation doesn't work like interruption. Cancellation is a different model than interruption.

Could you explain the distinction between cancellation and interruption? I have understood them to be synonymous terms in the context of Scala effect types.

> or right after (but before the print line)
I'm not sure what the implementation of `*>` is, but if it is defined in terms of `flatMap`, does that mean every `flatMap` is a boundary that is considered for cancellation?

**Comment by jdegoes** [comment] 2018-10-08 01:55
> Both of those sequences of execution seem intuitive to me. My expectation was that release cannot begin until use completes, which ZIO seems to satisfy.

Yes, that's correct.

> I suppose a decision had to be made for IO to execute finalizers immediately in the face of things like non-terminating tasks.

The problem is that a non-terminating task is indistinguishable from a long-running task, and there's no way the runtime can know (or even know if it's possible to release a resource without first waiting for `use` to finish), so rather than make assumptions that violate consistency and predictability, ZIO guarantees the finalizer (_release_) will not execute until either `use` completes, or terminates due to error or interruption. This means that if `use` is uninterruptible, begins execution, and then runs forever (e.g. `IO.delay(while(true){})`), the finalizer will never run.

IMO this is the best default, because not only does this preserve linearity (and along with it, consistency and predictability), but a user can always timeout the use action themselves _if_ that's desired (e.g. `use.timeout(60.seconds)`). In other words, the ZIO default is the orthogonal choice, because timeout (i.e. the possibility of runaway `use` tasks) can be layered in separately as desired by the user.

> What is ZIO's behavior when you interrupt/cancel a bracket operation where use is non-terminating (ZIO equivalent of IO.never)?

Async operations are atomically and lock-lessly disconnected from their callbacks (and if possible, the underlying asynchronous operation is cancelled). This means that `IO.never`, like `IO.sleep`, can be interrupted, and code like `acquire.bracket(release)(IO.never)` works as expected (the finalizer is invoked).

There are two ways a finalizer can fail to run: 

 1. The `use` action is an infinite synchronous / blocking operation, e.g. `IO.delay(while(true){})`. These cannot be interrupted and it cannot be known by the runtime if they will ever terminate.
 2. The `use` action is an uninterruptible infinite asynchronous, e.g. `IO.uninterruptible(IO.never)` (this is an asynchronous operation that, while ordinarily interruptible, even if infinite, has been made uninterruptible through the `uninterruptible` combinator).

If the `use` action is not uninterruptible infinite asynchronous or infinite synchronous, then the finalizer will always be run, even if other finalizers have failed or there are defects in the tasks or finalizers.

> Could you explain the distinction between cancellation and interruption? I have understood them to be synonymous terms in the context of Scala effect types.

Interruption is a feature that allows the runtime system to immediately stop interpreting the spine of an `IO` action, so long as the following two criteria are satisfied:

1. The `IO` action has not been made uninterruptible via the `uninterruptible` combinator.
2. All finalizers currently registered will be run "on the way out" in the correct, linear order should the runtime decide to stop executing the `IO` action.

Cancellation used to have a model (e.g. it could occur at cancelation boundaries and would be required to invoke the canceler), but the current `cats-io` has a hybrid of the old cancelation model and a new "auto-cancelable binds" feature inspired from Monix. I'm not sure it can be easily described (especially in the context of `bracket`, whose presence changes semantics of operations like fiber join and linearity guarantees) without reference to the code.

> I'm not sure what the implementation of *> is, but if it is defined in terms of flatMap, does that mean every flatMap is a boundary that is considered for cancellation?

Not just every `flatMap`, but potentially every operation on an `IO`. The runtime system interprets the spine of an `IO` operation-by-operation, which allows it to stop interpreting instantaneously between any pair of operations (`flatMap` is just one of a handful of different core operation types).

`*>` is required to be equal to `left.flatMap(_ => right)`, just like `<*` is required to be equal to `left.flatMap(v => right.map(_ => v))`, but even if these were special-cased in ZIO, they would still be operations interpreted by the runtime system and would therefore be interruptible by default.

If these defaults seem to match what you're looking for, you should give ZIO a try, since it already has instances for `cats-effect` 1.0 in the separate-but-bundled `interop` package.

**Comment by alexandru** [comment] 2018-10-08 05:57
> IMO this is the best default, because not only does this preserve linearity (and along with it, consistency and predictability), but a user can always timeout the use action themselves if that's desired (e.g. use.timeout(60.seconds)). In other words, the ZIO default is the orthogonal choice, because timeout (i.e. the possibility of runaway use tasks) can be layered in separately as desired by the user.

Timeout in this case also creates a leak. It is true that in case of a `while (true) {}` there isn't much that you could do in `release`, however many times there is something you can do and the model exposed by Cats-Effect IO and Monix allows better interop:

```scala
import monix.execution.Atomic
import monix.eval.Task

Task(Atomic(true)).bracket { isActive => 
  Task {
    while (isActive.get) {}
  }
} { isActive =>
  Task(isActive.set(true)) 
}
```

And in most cases you can trivially order `release` after `use` on cancellation or even distinguish when cancellation occurs such that different logic can be triggered, which is what the `ExitCase.Canceled` is for.

**Comment by jdegoes** [comment] 2018-10-08 11:14
> It is true that in case of a while (true) {} there isn't much that you could do in release, however many times there is something you can do and the model exposed by Cats-Effect IO and Monix allows better interop:

That's not true. Either model allows you to check a boolean flag in a synchronous while loop based on interruption status.

However, in only one model—the ZIO model—do you have the guarantee that `release` occurs after `use` (not concurrently), and that `bracket` functions identically across (trivially uninterruptible) synchronous infinite tasks and (explicitly uninterruptible) asynchronous infinite tasks.

I'd argue these properties allow a consistent and predictable user experience (though time will be the judge of that).
