### ISSUE TITLE
effects specified with IO.apply are unexpectedly running on the blocker pool

### ISSUE THREAD

**Issue by arosien** [typelevel/cats-effect#3316] opened 2022-12-15 21:05 UTC
I'm running printing the current thread name via `println` delayed via `IO.apply`--*not* `IO.println`!--and I unexpectedly see the printing happening on the blocker threads:
```scala
object Blocking extends IOApp {
  def run(args: List[String]): IO[ExitCode] =
    for {
      // _ <- IO.cede
      _ <- IO(println(s"${Thread.currentThread.getName} default"))
      _ <- IO.blocking(println(s"${Thread.currentThread.getName} blocking"))
      _ <- IO(println(s"${Thread.currentThread.getName} default"))
    } yield ExitCode.Success
}
```
prints
```
io-compute-blocker-3 default
io-compute-blocker-3 blocking
io-compute-blocker-3 default
```
(the blocker thread number various across runs; this is cats-effect 3.4.2)

I expect the printing of `default` on the `io-compute` pool, not the `io-compute-blocker` pool.

If I uncomment the `cede`, I get the following output:
```
io-compute-1 default
io-compute-blocker-1 blocking
io-compute-blocker-1 default
```
which correctly prints the first `default`, but again the second one is unexpectedly on the blocker pool.

This reminds me of the "callback running on the external thread pool" problem of CE2, requiring an `IO.shift`, but it may only be superficially related.

**Comment by vasilmkd** [comment] 2022-12-15 21:30
It's a bug in the thread renaming logic. It still runs on the compute pool.

**Comment by armanbilge** [comment] 2022-12-16 05:57
Isn't this exactly the expected behavior? When a worker thread becomes a blocking thread, it will continue executing the fiber past the `blocking` until the next (auto-)`cede` or `async` reschedules the fiber on the compute pool.

Here's a demo program where you can see the auto-cede kick in.

```scala
//> using lib "org.typelevel::cats-effect::3.4.2"

import cats.effect._
import cats.syntax.all._

object Blocking extends IOApp {
  def run(args: List[String]): IO[ExitCode] =
    for {
      _ <- IO(println(s"${Thread.currentThread.getName} before"))
      _ <- IO.blocking(println(s"${Thread.currentThread.getName} blocking"))
      _ <- List.range(0, 250).traverse_ { i =>
        IO(println(s"${Thread.currentThread.getName} after $i"))
      }
    } yield ExitCode.Success
}
```

<details>

```
io-compute-blocker-5 before
io-compute-blocker-5 blocking
io-compute-blocker-5 after 0
io-compute-blocker-5 after 1
io-compute-blocker-5 after 2
io-compute-blocker-5 after 3
io-compute-blocker-5 after 4
io-compute-blocker-5 after 5
io-compute-blocker-5 after 6
io-compute-blocker-5 after 7
io-compute-blocker-5 after 8
io-compute-blocker-5 after 9
io-compute-blocker-5 after 10
io-compute-blocker-5 after 11
io-compute-blocker-5 after 12
io-compute-blocker-5 after 13
io-compute-blocker-5 after 14
io-compute-blocker-5 after 15
io-compute-blocker-5 after 16
io-compute-blocker-5 after 17
io-compute-blocker-5 after 18
io-compute-blocker-5 after 19
io-compute-blocker-5 after 20
io-compute-blocker-5 after 21
io-compute-blocker-5 after 22
io-compute-blocker-5 after 23
io-compute-blocker-5 after 24
io-compute-blocker-5 after 25
io-compute-blocker-5 after 26
io-compute-blocker-5 after 27
io-compute-blocker-5 after 28
io-compute-blocker-5 after 29
io-compute-blocker-5 after 30
io-compute-blocker-5 after 31
io-compute-blocker-5 after 32
io-compute-blocker-5 after 33
io-compute-blocker-5 after 34
io-compute-blocker-5 after 35
io-compute-blocker-5 after 36
io-compute-blocker-5 after 37
io-compute-blocker-5 after 38
io-compute-blocker-5 after 39
io-compute-blocker-5 after 40
io-compute-blocker-5 after 41
io-compute-blocker-5 after 42
io-compute-blocker-5 after 43
io-compute-blocker-5 after 44
io-compute-blocker-5 after 45
io-compute-blocker-5 after 46
io-compute-blocker-5 after 47
io-compute-blocker-5 after 48
io-compute-blocker-5 after 49
io-compute-blocker-5 after 50
io-compute-blocker-5 after 51
io-compute-blocker-5 after 52
io-compute-blocker-5 after 53
io-compute-blocker-5 after 54
io-compute-blocker-5 after 55
io-compute-blocker-5 after 56
io-compute-blocker-5 after 57
io-compute-blocker-5 after 58
io-compute-blocker-5 after 59
io-compute-blocker-5 after 60
io-compute-blocker-5 after 61
io-compute-blocker-5 after 62
io-compute-blocker-5 after 63
io-compute-blocker-5 after 64
io-compute-blocker-5 after 65
io-compute-blocker-5 after 66
io-compute-blocker-5 after 67
io-compute-blocker-5 after 68
io-compute-blocker-5 after 69
io-compute-blocker-5 after 70
io-compute-blocker-5 after 71
io-compute-blocker-5 after 72
io-compute-blocker-5 after 73
io-compute-blocker-5 after 74
io-compute-blocker-5 after 75
io-compute-blocker-5 after 76
io-compute-blocker-5 after 77
io-compute-blocker-5 after 78
io-compute-blocker-5 after 79
io-compute-blocker-5 after 80
io-compute-blocker-5 after 81
io-compute-blocker-5 after 82
io-compute-blocker-5 after 83
io-compute-blocker-5 after 84
io-compute-blocker-5 after 85
io-compute-blocker-5 after 86
io-compute-blocker-5 after 87
io-compute-blocker-5 after 88
io-compute-blocker-5 after 89
io-compute-blocker-5 after 90
io-compute-blocker-5 after 91
io-compute-blocker-5 after 92
io-compute-blocker-5 after 93
io-compute-blocker-5 after 94
io-compute-blocker-5 after 95
io-compute-blocker-5 after 96
io-compute-blocker-5 after 97
io-compute-blocker-5 after 98
io-compute-blocker-5 after 99
io-compute-blocker-5 after 100
io-compute-blocker-5 after 101
io-compute-blocker-5 after 102
io-compute-blocker-5 after 103
io-compute-blocker-5 after 104
io-compute-blocker-5 after 105
io-compute-blocker-5 after 106
io-compute-blocker-5 after 107
io-compute-blocker-5 after 108
io-compute-blocker-5 after 109
io-compute-blocker-5 after 110
io-compute-blocker-5 after 111
io-compute-blocker-5 after 112
io-compute-blocker-5 after 113
io-compute-blocker-5 after 114
io-compute-blocker-5 after 115
io-compute-blocker-5 after 116
io-compute-blocker-5 after 117
io-compute-blocker-5 after 118
io-compute-blocker-5 after 119
io-compute-blocker-5 after 120
io-compute-blocker-5 after 121
io-compute-blocker-5 after 122
io-compute-blocker-5 after 123
io-compute-blocker-5 after 124
io-compute-blocker-5 after 125
io-compute-blocker-5 after 126
io-compute-blocker-5 after 127
io-compute-blocker-5 after 128
io-compute-blocker-5 after 129
io-compute-blocker-5 after 130
io-compute-blocker-5 after 131
io-compute-blocker-5 after 132
io-compute-blocker-5 after 133
io-compute-blocker-5 after 134
io-compute-blocker-5 after 135
io-compute-blocker-5 after 136
io-compute-blocker-5 after 137
io-compute-blocker-5 after 138
io-compute-blocker-5 after 139
io-compute-blocker-5 after 140
io-compute-blocker-5 after 141
io-compute-blocker-5 after 142
io-compute-blocker-5 after 143
io-compute-blocker-5 after 144
io-compute-blocker-5 after 145
io-compute-blocker-5 after 146
io-compute-blocker-5 after 147
io-compute-blocker-5 after 148
io-compute-blocker-5 after 149
io-compute-blocker-5 after 150
io-compute-blocker-5 after 151
io-compute-blocker-5 after 152
io-compute-blocker-5 after 153
io-compute-blocker-5 after 154
io-compute-blocker-5 after 155
io-compute-blocker-5 after 156
io-compute-blocker-5 after 157
io-compute-blocker-5 after 158
io-compute-blocker-5 after 159
io-compute-blocker-5 after 160
io-compute-blocker-5 after 161
io-compute-blocker-5 after 162
io-compute-blocker-5 after 163
io-compute-blocker-5 after 164
io-compute-blocker-5 after 165
io-compute-blocker-5 after 166
io-compute-blocker-5 after 167
io-compute-blocker-5 after 168
io-compute-blocker-5 after 169
io-compute-blocker-5 after 170
io-compute-blocker-5 after 171
io-compute-blocker-5 after 172
io-compute-blocker-5 after 173
io-compute-blocker-5 after 174
io-compute-blocker-5 after 175
io-compute-blocker-5 after 176
io-compute-blocker-5 after 177
io-compute-blocker-5 after 178
io-compute-blocker-5 after 179
io-compute-blocker-5 after 180
io-compute-blocker-5 after 181
io-compute-blocker-5 after 182
io-compute-blocker-5 after 183
io-compute-blocker-5 after 184
io-compute-blocker-5 after 185
io-compute-blocker-5 after 186
io-compute-blocker-5 after 187
io-compute-blocker-5 after 188
io-compute-blocker-5 after 189
io-compute-blocker-5 after 190
io-compute-blocker-5 after 191
io-compute-blocker-5 after 192
io-compute-blocker-5 after 193
io-compute-blocker-5 after 194
io-compute-blocker-5 after 195
io-compute-blocker-5 after 196
io-compute-blocker-5 after 197
io-compute-blocker-5 after 198
io-compute-blocker-5 after 199
io-compute-blocker-5 after 200
io-compute-blocker-5 after 201
io-compute-blocker-5 after 202
io-compute-blocker-5 after 203
io-compute-blocker-5 after 204
io-compute-blocker-5 after 205
io-compute-blocker-5 after 206
io-compute-blocker-5 after 207
io-compute-blocker-5 after 208
io-compute-blocker-5 after 209
io-compute-blocker-5 after 210
io-compute-blocker-5 after 211
io-compute-blocker-5 after 212
io-compute-blocker-5 after 213
io-compute-blocker-5 after 214
io-compute-blocker-5 after 215
io-compute-blocker-5 after 216
io-compute-blocker-5 after 217
io-compute-blocker-5 after 218
io-compute-blocker-5 after 219
io-compute-blocker-5 after 220
io-compute-blocker-5 after 221
io-compute-blocker-5 after 222
io-compute-blocker-5 after 223
io-compute-blocker-5 after 224
io-compute-blocker-5 after 225
io-compute-blocker-5 after 226
io-compute-blocker-5 after 227
io-compute-blocker-5 after 228
io-compute-blocker-5 after 229
io-compute-blocker-5 after 230
io-compute-blocker-5 after 231
io-compute-blocker-5 after 232
io-compute-blocker-5 after 233
io-compute-blocker-5 after 234
io-compute-blocker-5 after 235
io-compute-blocker-5 after 236
io-compute-blocker-5 after 237
io-compute-blocker-5 after 238
io-compute-blocker-5 after 239
io-compute-blocker-5 after 240
io-compute-blocker-5 after 241
io-compute-blocker-5 after 242
io-compute-blocker-5 after 243
io-compute-blocker-5 after 244
io-compute-15 after 245
io-compute-15 after 246
io-compute-15 after 247
io-compute-15 after 248
io-compute-15 after 249
```

</details>

**Comment by armanbilge** [comment] 2022-12-16 06:04
Furthermore, note that one of the first things `IOApp` does before running the user-defined program is `blocking`. This is why the fiber initially starts on a blocking thread, and `cede`-ing as the first step sends it back to the compute pool. 

https://github.com/typelevel/cats-effect/blob/52b5a3ba1623ff40fc48318c9a0bfae558f0e5ed/core/jvm/src/main/scala/cats/effect/IOApp.scala#L373-L383

https://github.com/typelevel/cats-effect/blob/52b5a3ba1623ff40fc48318c9a0bfae558f0e5ed/core/jvm/src/main/scala/cats/effect/metrics/JvmCpuStarvationMetrics.scala#L55-L60

**Comment by djspiewak** [comment] 2022-12-24 23:18
This is a surprisingly easy issue to fix, so I'll mark it as such. There are two approaches here, and either are acceptable:

- Move the mbean initialization out of `blocking` and into `delay`/`apply` (since we know nothing is running yet, so we can cheat on blocking stuff)
- Add an `IO.cede` to kick us back to the compute pool

Technically, the former approach will produce slightly better performance.

**Comment by mox692** [comment] 2023-01-02 05:34
I'm interested in this issue, and I want to try it :)

**Comment by armanbilge** [comment] 2023-01-02 05:37
@mox692 go for it 🚀

**Comment by decoursin** [comment] 2023-01-19 14:10
I saw the changes of #3342, I tried tag 3.4.5, which has those changes, but I'm still getting this with IO.cede commented out:
```
io-compute-1 default
io-compute-blocker-1 blocking
io-compute-blocker-1 default
```

**Comment by armanbilge** [comment] 2023-01-19 14:22
@decoursin what is the exact code you are running?

In any case I am nearly positive this is the expected result :)

> When a worker thread becomes a blocking thread, it will continue executing the fiber past the blocking until the next (auto-)cede or async reschedules the fiber on the compute pool.

https://github.com/typelevel/cats-effect/issues/3316#issuecomment-1354263918

**Comment by decoursin** [comment] 2023-01-19 16:29
I don't have it anymore, but it was you have above.

I noticed that there's another strange IO.blocking right below the one @mox692 removed. Maybe that's the culprit? I don't know. https://github.com/mox692/cats-effect/blob/series/3.x/core/jvm/src/main/scala/cats/effect/metrics/JvmCpuStarvationMetrics.scala#L64

**Comment by armanbilge** [comment] 2023-01-19 16:36
> I noticed that there's another strange IO.blocking right below the one @mox692 removed.

That one is part of the resource release phase, so I expect it only run when the program shuts down. Actually I'm not sure if we need blocking there anyway /shrug

Anyway, looks like we forgot to close this issue even though it was fixed. Please don't hesitate to open a new one if you have a reproducer :)

**Closed as completed by armanbilge** 2023-01-19 16:36 UTC
Labels: good first issue, :books: docs

**Comment by armanbilge** [comment] 2023-01-19 17:10
I opened a PR adding an FAQ entry about this:
- https://github.com/typelevel/cats-effect/pull/3378
