### ISSUE TITLE
Old API links are broken and need redirection

### ISSUE THREAD

**Issue by arosien** [typelevel/cats-effect#1856] opened 2021-03-29 21:40 UTC
Previous scaladoc links point to https://typelevel.org/cats-effect/api/*, which are now hosted at https://typelevel.org/cats-effect/api/2.x/*. Add a redirect?

Also, perhaps the https://typelevel.org/cats-effect/api page should exist and have links to 2.x and 3.x sub-hierarchies.

**Comment by djspiewak** [comment] 2021-03-30 17:51
https://stackoverflow.com/questions/10178304/what-is-the-best-approach-for-redirection-of-old-pages-in-jekyll-and-github-page

This is the best I can find :-/

**Comment by bjaglin** [comment] 2021-04-01 12:36
duplicate of https://github.com/typelevel/cats-effect/issues/1843?

**Comment by kubukoz** [comment] 2021-04-02 19:22
Yeah.

**Closed as completed by kubukoz** 2021-04-02 19:22 UTC
Labels: :books: docs
