### ISSUE TITLE
Reduce ceremony in declaring ExecutionContext for IOApp

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats-effect#337] opened 2018-09-01 05:09 UTC
The default `IOApp` uses the global execution context for `contextShift` and `timer`.  If we create our own, and want to use it for the `ContextShift` and `Timer` instances, there are three ceremonies to perform:

```scala
  protected implicit val executionContext: ExecutionContextExecutorService =
    ExecutionContext.fromExecutorService(Executors.newFixedThreadPool(8))

  protected override implicit lazy val contextShift: ContextShift[IO] =
    IO.contextShift(executionContext) // ceremony 1

  protected override implicit lazy val timer: Timer[IO] =
    IO.timer(executionContext) // ceremony 2

  def run(args: List[String]): IO[ExitCode] =
    businessLogic
      .guarantee(IO(executionContext.shutdown())) // ceremony 3
      .as(ExitCode.Success)
```

If the trait defined an `ExecutionContext`, we might eliminate ceremonies 1 and 2, but we'd have to be thoughtful about laziness.

A template method, or abstract overrides, might eliminate ceremony 3, but would be unidiomatic for this project.

Going to sleep on this and hope to dream of something cleaner.

**Comment by alexandru** [comment] 2018-09-01 10:14
All those params are horrible IMO. How about a helper:

```scala
object IOApp {

  abstract class WithContext(ec: ExecutionContext) {
    //...
  }
}
```

And then you have to do:

```scala
import scala.concurrent.ExecutionContext.global

object Main extends IOApp.WithContext(global) {
  //...
}
```

**Comment by alexandru** [comment] 2018-09-01 10:51
OK this doesn't solve your problem. You want to create a thread pool, possibly non-daemonic which means that it can block the shutdown of the application and you want to shut it down on exit.

The problem is that this makes `IOApp` break referential transparency. So for example invoking `main` twice won't work. You can't have the logic in `IOApp` to automatically shut down the thread-pool.

It's probably a bad idea to shut down that thread pool because you're running on top of it so after `shutdown` it won't accept any new Runnables. Looking at the code in `IOAppPlatform` I don't think it's a problem since the application is supposed to exit, but I'm not sure; I guess that we no longer have anything to execute afterwards, so in the context of `IOApp`'s usage it might be OK, but for example we might have problems guaranteeing the correct behavior of `IO[ExitCode]` when we invoke that `run` as a simple function.

In general shutting down the thread pool on top of which you run is a bad idea, I just joked about it on Twitter yesterday 🙂 https://twitter.com/alexelcu/status/1035423701288804352

**Comment by alexandru** [comment] 2018-09-01 10:56
Not sure what to do about this, was just saying that your sample is not OK.

```scala
trait IOApp {
  def executionContext: Resource[ExecutionContext]

  def run(args: List[String])(implicit cs: ContextShift[IO], timer: Timer[IO]): IO[ExitCode]
}
```

And maybe something like this isn't awful?

**Comment by SystemFw** [comment] 2018-09-01 15:42
We're getting pretty close to "RTS" (or whatever you want to call it) with that :)

**Comment by ChristopherDavenport** [comment] 2018-09-01 17:43
I'm inclined towards the last suggestion. Seems the one that offers the most flexibility while still offering the utility.

**Comment by rossabaker** [comment] 2018-09-01 17:45
I had been trying to do this without `Resource` for two reasons:
1. The default, global `ExecutionContext` can't be shut down.  As a `Resource`, `using` it can leave behind more threads than we started with.
2. I couldn't figure out how to do it without forcing the `ContextShift` and `Timer`.  But the former happens anyway: we don't run `run` on the main thread, but rather with `start(contextShift.value)`.  We're going to have an `ExecutionContext` no matter what.

I think your design isn't awful.  The question is the default: create our own default that properly shuts down, or default to the global?  I lean toward the former: I strongly dislike the main pool being daemonic.

**Comment by rossabaker** [comment] 2018-09-01 17:48
That `run` signature also makes it difficult to reference the `ExecutionContext` from `run` for anything but the `ContextShift` and `Timer`.  I'm reluctant to introduce a third implicit.

**Comment by rossabaker** [comment] 2018-09-01 17:54
This design would also cost us the ability to provide (and avoid our default) `ScheduledExecutorService` for the `Timer`.

**Comment by alexandru** [comment] 2018-09-01 20:25
I have an argument against usage of a `Resource[IO, ExecutionContext]`. It's not a problem right now, but it might become in the future, this being about how future proof the API is.

I experimented with this in Monix and I cannot use `Resource[Task, Scheduler]` in `TaskApp`. This is because `Task` requires a `Scheduler` to execute. No `Scheduler`, no ability to execute, being a necessary requirement.

For `IO` the *only reason* we can afford it is because `unsafeRunSync()` doesn't require it. Which is awesome, I like this design, but can it survive one or two major versions? I honestly don't know.

But that it doesn't work for Monix's `Task` is proof of what I said: this thread pool needs to survive for the whole duration of the app.

I'm thinking that we shouldn't do anything, at least with the main `trait`.

We can then provide subtypes like `IOApp.WithContext`. How exactly such a subtype can work, not absolutely sure, but it can be added later.

**Comment by SystemFw** [comment] 2018-09-01 20:28
> For IO the only reason we can afford it is because unsafeRunSync() doesn't require it. Which is awesome, I like this design, but can it survive one or two major versions? I honestly don't know.

fwiw, I think this is limiting and I prefer the Scheduler approach, as I've said countless times. So if the proposed design doesn't work for that, that's a strong argument imho.

Ofc, we could have it now and change it later

**Comment by rossabaker** [comment] 2018-09-01 20:32
Observations:
* `IOApp.main` requires a `ContextShift` on the JVM. The `Timer` is lazy.
* `IOApp.main` requires a `ContextShift` and a `Timer` on ScalaJS.
* It's  preferred that `ContextShift` and `Timer` are both derived from a common `ExecutionContext`.
* That same `ExecutionContext` is useful when apps interact with `Future`.

If we can cleanly configure an `ExecutionContext`, and make it visible and live through the duration of `run`, we end up in a good place for everything but the customization and cleanup of the `ScheduledExecutorService` used by the default `Timer`.  There is a weaker case for making that scheduler, as opposed to the `Timer`, visible to `run`.

**Comment by alexandru** [comment] 2018-09-01 20:38
How about something like this:

```scala
object IOApp {

  trait WithContext extends IOApp {
    protected def executionContext: ExecutionContext

    override lazy val contextShift = IO.contextShift(executionContext)
    override lazy val timer = IO.timer(executionContext)
  }
}
```

**Comment by rossabaker** [comment] 2018-09-01 20:41
Where do we shut it down if it's non-daemonic?  It's dangerous to do it in `run` (though my initial example worked), and we have no other hook.

**Comment by rossabaker** [comment] 2018-09-01 21:12
I think making the runtime available as global values when they depend on values that should be managed is the friction point here.  I liked the idea of providing the runtime to `run`, and letting `main` acquire it.  The question, then, it's what's the runtime?

* `ContextShift[IO]`: always required
* `Timer[IO]`: required only by ScalaJS
* `ExecutionContext`: sufficient for `ContextShift` and `Timer`, necessary for `Future` interop
* `ScheduledExecutorService`: nice for configuring `Timer`, doesn't work(?) on ScalaJS

Maybe:

```scala
trait IORuntime {
  // maybe make these implicit
  def executionContext: ExecutionContext
  def timer: Timer[IO]
  def contextShift: ContextShift[IO]
}

trait IOApp extends IOAppPlatform {
  def executionResource: Resource[IO, ExecutionContext]

  def run(runtime: IORuntime, args: List[String]): IO[Unit]

  def main(args: List[String]) =
    executionResource.use { ec =>
      // on JVM, also use schedulerResource to create the `IORuntime`
      val runtime = IORuntime(ec)
      runtime.cs.shift *> run(args, runtime)
    }
}

trait IOAppPlatform { // on JVM
  def schedulerResource: Resource[IO, ScheduledExecutorService]
}
```

Flaws:
* Forces `ScheduledExecutorService` on the JVM
* Hides `ScheduledExecutorService` in rare Java interop that needs it
* Have to import from `runtime._` in `run` to use them implicitly

**Comment by alexandru** [comment] 2018-09-01 21:26
> Where do we shut it down if it's non-daemonic? It's dangerous to do it in run (though my initial example worked), and we have no other hook.

If your sample worked, then maybe that's what we should do. My objection was that I can't figure out if there are any more Runnables submitted in that thread-pool after shutdown. This is one of those cases in which it's a good thing that `IO` doesn't automatically fork, because with Monix's `Task` a subsequent `flatMap` could prove to be problematic.

Another possibility would be in `IOAppPlatform.main` We could pass in that function an `IO[Unit]` meant for cleaning up resources.

---

What does `IORuntime` solve?  Having to import anything in `run` is a huge turn-off because the whole point of using `IOApp` is for users to have everything they need in `run` and for things to just work.

The main problem is that the main thread-pool is not a `Resource`, unless `IOApp` also is.

**Comment by rossabaker** [comment] 2018-09-01 23:00
If we created an implicit Timer and ContextShift from an implicit ExecutionContext, and defined an ExecutionContext resource, we:

* would only need to pass one thing to run
* could summon a consistent ContextShift and Timer without ceremony
* could create a custom Timer from a ScheduledExecutorService in run, only where useful
* could use a non-daemon pool without shutting it down in run

We would lose:
* the ability to customize the context shift in main, though it would be based on the ExecutionContext
* the ability to customize the timer that keeps alive the ScalaJS app in main

**Comment by alexandru** [comment] 2018-09-03 09:17
@rossabaker how about something like this:
https://gist.github.com/alexandru/f8964547c190f39263962c52aedd6ae3

Advantages:

1. the current `IOApp` stays as it is
2. this is a subtype that works only for the JVM

Usage:

```scala
object Main extends IOApp.WithContext {
  val contextBuilder = Resource.liftF(SyncIO(ExecutionContext.global))
  val schedulerBuilder = Resource(SyncIO( .... ))
}
```

**Comment by rossabaker** [comment] 2018-09-03 19:10
Some benchmarks of `ContextShift` using `AtomicExecutionContext`.  I adapted `AsyncBenchmark.start` and `ShallowBenchmark.async` to do some heavy shifting:

```
[info] ECBenchmark.asyncAtomic  thrpt   20  16042.244 ± 361.970  ops/s
[info] ECBenchmark.asyncPlain   thrpt   20  16420.229 ± 276.031  ops/s
[info] ECBenchmark.startAtomic  thrpt   20   5748.333 ± 337.159  ops/s
[info] ECBenchmark.startPlain   thrpt   20   5819.467 ± 142.843  ops/s
```

**Comment by alexandru** [comment] 2018-09-04 07:27
Hi guys, so after sleeping on it, I'm still bothered by `IOApp` not being pure.

I'm now thinking that proposal #341 isn't that bad, but it can use improvements:

1. one thing that bothers me about using a `Runtime` is that users would have to then import from it. That sucks from an API standpoint, but we can use implicit "extractors", which we already did for extracting a `Clock` out of a `Timer`: https://gist.github.com/alexandru/e45231fddb42c77c830695aadaf6dbb9
2. the default `IOApp` should not expose any `Resource` values, as it should use the current defaults under the hood; `Resource` only makes sense on the JVM, so we can do like in #344 and expose an additional `IOApp.WithContext`, available only on the JVM, that uses `Resource[SyncIO]` objects for customizing those defaults
  - N.B. the base `IOApp` trait should still be common between the JVM and JS.

Advantages:

1. `IOApp` becomes pure-er, easier to test, as we no longer rely on shared state (not sure how important this is since `IOApp` provides the "environment" and the "environment" isn't pure, IOApp being meant to be a singleton)
2. It follows the pattern that we encourage users to use, i.e. don't use globals, pass them as parameters

Disadvantages:

1. we have to abuse implicits because otherwise the API sucks
  - I don't want us to tell users to import anything, `extends IOApp` should be the only import they need
2. we change `IOApp` yet again and @rossabaker is probably not happy after closing #341 and deleting his branch 😂

Sorry for throwing wood on fire, but I'm thinking that in order to make the best decision possible, we'll need to do a vote. Thinking it's either #344, or #341 with these suggestions.

**Comment by rossabaker** [comment] 2018-09-04 13:46
I like how we persuaded one another to lean toward the other's idea. :laughing: 

I think I've made my peace with the lack of purity in `IOApp`, which is intended to be "the end of the world."  What can go wrong, really?  The constructor using the `ExecutionContext`?

I tried the runtime "extractor" implicits and felt bad. I also tried passing `ec`, `cs`, and `timer` as individual implicits.  This makes an ugly `run` signature -- the thing that everybody needs to implement -- and also forecloses making the scheduler part of the JVM's `Runtime`, or other future changes to what constitutes the runtime.  I think the extractors are the way to go in the pure model.

On #341, are you proposing that `IOApp.WithContext#run` has a `Runtime` while `IOApp#run` does not?  If not, and everything has a `Runtime` parameter, then I don't see much reason to make `WithContext` separate.  The two `IOApp`s would be unified in their abstract method, and be source compatible in their default configurations, but diverge in their customization to reflect the divergent platforms.  (I [imagined similar](https://github.com/typelevel/cats-effect/pull/344#issuecomment-418194543) in the impure model).  I lean toward this flattening either way.

I see two mostly orthogonal issues:
- The purity of #344 vs. the simplicity and source compatibility of #341 
- `WithContext` vs. platform-specific configuration of `IOApp`s that share a `run`

My leaning is #344 and no `WithContext`, but I don't hate any of the 2x2 options.

**Comment by alexandru** [comment] 2018-09-04 14:07
@rossabaker I think you got them mixed.

So which do you prefer?

**Comment by rossabaker** [comment] 2018-09-04 16:16
I stated the correct preference but flipped their descriptions.  I like the impure (#344) better than the pure (#341).

Flattening the hierarchy does not preclude the global executor as the default to serve the 80%.  And exiling it to a trait does not yield uniform semantics in vanilla `IOApp`: the only way to emulate scala.js' draining of the task queue on the JVM is to customize the resource.  It adds no abstract methods to the 80%.  The costs of flattening to the 80% are impurity, a forced scheduler instantiation, and making it harder to design other mix-ins.

We can flatten this later without breaking source compatibility, but we can't unflatten it, so I'll amend my vote to #344 and keep `WithContext`.

**Comment by johnynek** [comment] 2018-09-04 16:38
I wonder if Resource with SyncIO can be useful to bootstrap here. If we had a method to run on IO to get a SyncIO, then I think we can safely always run a SyncIO without an ExecutionContext.

Just a thought that may be of use.

**Closed** 2018-09-05 05:56 UTC
