### ISSUE TITLE
`WorkerNameSpec` is flaky in CI

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats-effect#3482] opened 2023-03-07 22:12 UTC
```
[info] WorkerThreadNameSpec
[3010](https://github.com/typelevel/cats-effect/actions/runs/4357659637/jobs/7617244006#step:23:3011)
[info] WorkerThread should
[3011](https://github.com/typelevel/cats-effect/actions/runs/4357659637/jobs/7617244006#step:23:3012)
[error]   x rename itself when entering and exiting blocking region
[3012](https://github.com/typelevel/cats-effect/actions/runs/4357659637/jobs/7617244006#step:23:3013)
[error]    blocker thread not found after reset (WorkerThreadNameSpec.scala:75)
[3013](https://github.com/typelevel/cats-effect/actions/runs/4357659637/jobs/7617244006#step:23:3014)
[info] Total for specification WorkerThreadNameSpec
[3014](https://github.com/typelevel/cats-effect/actions/runs/4357659637/jobs/7617244006#step:23:3015)
```

**Comment by armanbilge** [comment] 2023-03-07 23:09
Dupe of https://github.com/typelevel/cats-effect/issues/3216 ? :)

**Closed as not planned by armanbilge** 2023-03-07 23:09 UTC
