### ISSUE TITLE
Racing Resource causes exception to be printed in standard error

### ISSUE THREAD

**Issue by lavrov** [typelevel/cats-effect#3086] opened 2022-07-10 09:41 UTC
Reproduction script (scala-cli):
```scala
//> using lib "org.typelevel::cats-effect:3.3.13"

import cats.effect.*

object Main extends IOApp.Simple:

  def run =
    Resource
      .eval(IO.raiseError(new Exception("Boom")))
      .race(Resource.never)
      .attempt
      .use(_ => 
        IO.println("Done")
      )
```
Running `scala-cli run main.scala` gives the following output:
```
java.lang.Exception: Boom
	at Main$.run(main.scala:9)
	at run$ @ Main$.run(main.scala:5)
Done
```
where exception stacktrace comes from standard error.

**Comment by armanbilge** [comment] 2022-07-10 09:44
Thanks for reporting. I think this may be related to https://github.com/typelevel/cats-effect/issues/2962 and https://github.com/typelevel/cats-effect/issues/3085.

**Comment by armanbilge** [comment] 2022-12-21 13:47
This still seems to be a problem as of 3.4.2. Maybe we can fix it as part of https://github.com/typelevel/cats-effect/pull/3226.

**Comment by djspiewak** [comment] 2023-02-27 17:52
@armanbilge Did we work around this with the specialized `race` implementation?

**Comment by armanbilge** [comment] 2023-02-27 17:59
Yup! Tried the reproducer with 3.4.2 and 3.4.3 when the new `race` implementation landed. The fix happened between there anyway :)

**Closed as completed by armanbilge** 2023-02-27 17:59 UTC
