### ISSUE TITLE
Dark mode doesn't like typeclass diagram

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats-effect#1659] opened 2021-02-08 11:13 UTC
We should add backgrounds or something...

![image](https://user-images.githubusercontent.com/894884/107212276-01a77880-6a07-11eb-83e1-1c530b19770f.png)

**Comment by vasilmkd** [comment] 2021-02-08 13:21
Duplicate of #1655.

**Closed as completed** 2021-02-08 13:21 UTC

**Comment by kubukoz** [comment] 2021-02-08 13:35
oh, sorry

**Comment by vasilmkd** [comment] 2021-02-08 13:43
No problem just cleaning up 😄

**Comment by djspiewak** [comment] 2021-02-08 14:07
You guys and your dark modes... 😃

**Comment by kubukoz** [comment] 2021-02-08 17:39
Light mode users be like

![image](https://user-images.githubusercontent.com/894884/107259129-ebb4aa80-6a3c-11eb-8b86-bf2adc8e4a33.png)
